version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sayhi
    volumes:
      - mysql_data:/var/lib/mysql

  # mongodb:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"

volumes:
  mysql_data:
